# JWT
app.jwt.secret=JusticeServeSecretKey2025SuperSecureBase64EncodedKeyForHMACSHA256Algorithm
app.jwt.expiration-ms=86400000

# CORS
app.cors.allowed-origins=http://localhost:4200

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers
management.endpoint.health.show-details=always
management.tracing.sampling.probability=0.1

# Logging
logging.level.org.springframework.security=WARN
logging.level.com.justiceserve=INFO

# ================================================================
# Resilience4j Circuit Breaker — for all Feign clients
# ================================================================
# Feign — enable circuit breaker
spring.cloud.openfeign.circuitbreaker.enabled=true
#spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
# Default circuit breaker settings (applies to all Feign clients)
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowSize=5
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=3
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10s
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.eventConsumerBufferSize=10

# Specific circuit breakers per Feign client compliance-audit-service
resilience4j.circuitbreaker.instances.compliance-audit-service.baseConfig=default
resilience4j.circuitbreaker.instances.notification-service.baseConfig=default
resilience4j.circuitbreaker.instances.case-service.baseConfig=default
resilience4j.circuitbreaker.instances.user-service.baseConfig=default
resilience4j.circuitbreaker.instances.citizen-service.baseConfig=default

